### ISSUE TITLE
运行el_main的时候出错

### ISSUE THREAD

**Issue by Noizersam-sheng** [taishan1994/pytorch_bert_entity_linking#1]
你好，请问了el_processs那几个文件之后，运行el_main出现了”Error no file named ['pytorch_model.bin, 'tf_model.h5, 'model.ckpt.index“是怎么回事，请问您可以给一些解答吗

**Comment by taishan1994** [comment]
> 你好，请问了el_processs那几个文件之后，运行el_main出现了”Error no file named ['pytorch_model.bin, 'tf_model.h5, 'model.ckpt.index“是怎么回事，请问您可以给一些解答吗

el_config.py里面有
```
parser.add_argument('--bert_dir', default='../model_hub/chinese-bert-wwm-ext/',
                            help='bert dir for uer')
```
你是否下载好然后指定了位置

**Comment by Noizersam-sheng** [comment]
![image](https://user-images.githubusercontent.com/60167653/140614529-d24bd648-311d-4d7d-845a-b4938b19d4d3.png)
请问【】里面的三个文件都要下载吗，我里面只有model.ckpt.index，其他两个文件如何下载呢

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/60167653/140614529-d24bd648-311d-4d7d-845a-b4938b19d4d3.png) 请问【】里面的三个文件都要下载吗，我里面只有model.ckpt.index，其他两个文件如何下载呢

config.py vocab.txt pytorch_model.bin

**Comment by Noizersam-sheng** [comment]
模型已经可以跑通了，谢谢您耐心地解答！！
