### ISSUE TITLE
作者你好，关于训练数据的来源

### ISSUE THREAD

**Issue by St-fcq** [taishan1994/pytorch_bert_entity_linking#2]
你好！
     有幸看到基于bert的实体链接代码，关于代码中训练集采用，train.pkl文件为啥不用train.json文件，还有这个.pkl文件是如何来的，里面的数据格式不是很懂，麻烦解答一下，谢谢

**Comment by taishan1994** [comment]
> 你好！ 有幸看到基于bert的实体链接代码，关于代码中训练集采用，train.pkl文件为啥不用train.json文件，还有这个.pkl文件是如何来的，里面的数据格式不是很懂，麻烦解答一下，谢谢

在el_preprocess.py里面，实际上是根据tran.json处理后得到的，为了避免每次训练时都要再处理一遍，就先生成结果并保存。

**Comment by suke6577** [comment]
你好，这个为什么会报错，小白才学。
IndexError: The shape of the mask [256] at index 0 does not match the shape of the indexed tensor [243, 768] at index 0
